const thankYouNotes = [
    "Thank you for your generosity and support!",
    "Your donation is making a real difference. Thank you!",
    "We appreciate your contribution and kindness. Thank you!",
    "Thank you for believing in our mission and for your support!",
    "Your donation means so much to us. Thank you!",
    "Your kindness and generosity are deeply appreciated. Thank you!",
    "We are grateful for your donation and for your belief in our cause. Thank you!",
    "Thank you for your support and for making a positive impact!",
    "Your donation is helping to create a brighter future for those in need. Thank you!",
    "We are touched by your generosity. Thank you for your donation!",
    "Thank you for your kindness and for being a part of our community!",
    "Your support is invaluable. Thank you for your donation!",
    "Thank you for your contribution and for being a part of our mission!",
    "Your donation is greatly appreciated. Thank you!",
    "We are humbled by your generosity. Thank you for your support!",
    "Thank you for your donation and for making a difference!",
    "Your support is a ray of hope for those in need. Thank you!",
    "We are grateful for your donation and for your belief in our cause. Thank you!",
    "Thank you for your generosity and for supporting our mission!",
    "Your donation is making a positive impact. Thank you!",
    "We appreciate your kindness and support. Thank you!",
    "Thank you for your contribution and for being a part of our community!",
    "Your support means the world to us. Thank you!",
    "Thank you for your generosity and for making a difference in our cause!",
    "Your donation is helping us achieve our goals. Thank you!",
    "We are touched by your kindness and generosity. Thank you!",
    "Thank you for your donation and for being a part of our mission!",
    "Your support is a beacon of hope for those in need. Thank you!",
    "We are grateful for your contribution and for your support. Thank you!",
    "Thank you for your generosity and for believing in our cause!",
    "Your donation is helping to create a brighter future. Thank you!",
    "We appreciate your kindness and support. Thank you for your donation!",
    "Thank you for your contribution and for being a part of our cause!",
    "Your donation is making a real difference. Thank you!",
    "We are humbled by your generosity and support. Thank you!",
    "Thank you for your donation and for making a positive impact!",
    "Your support means so much to us. Thank you!",
    "Thank you for your generosity and for being a part of our community!",
    "Your donation is helping to change lives. Thank you!",
    "We are grateful for your contribution and for your support. Thank you!",
    "Thank you for your kindness and for believing in our mission!",
    "Your donation is greatly appreciated. Thank you!",
    "We appreciate your generosity and support. Thank you for your donation!",
    "Thank you for your contribution and for making a difference!",
    "Your donation is helping us achieve our goals. Thank you!",
    "We are touched by your kindness and generosity. Thank you for your support!",
    "Thank you for your donation and for being a part of our cause!",
    "Your support is invaluable. Thank you!",
    "Thank you for your generosity and for your belief in our mission!",
    "Your donation is making a real impact. Thank you!",
    "We are grateful for your support and for making a difference. Thank you!",
]

export default thankYouNotes;